"use client";

import { ReactNode } from "react";
import { Provider } from "react-redux";
import { store } from "../../store/store";
import Navbar from "@/components/Navbar";
import Wrapper from "@/components/Wrapper";
import Header from "@/components/Header/Header";
import '../../styles/global.scss'

export default function RootLayout({children}: {children: ReactNode}){
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Wrapper>
            <Header/>
            <main>{children}</main>
            <footer></footer>
          </Wrapper>
          
        </Provider>
      </body>
    </html>
  )
}



















// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
